
### 1. User Management Endpoints

#### 1.1. Create Account (Sign Up)
POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.2@example.com",
  "password": "SecurePass123"
  
}

#### 1.2. Login true
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "john.2@example.com",
  "password": "SecurePass123"
}

#### 1.2.1 Login invalid
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "SecurePass123"
}


###find user
GET http://localhost:3000/users/1 HTTP/1.1
#### 1.3. Update User Profile
PUT http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json

{
  "name": "John Updated",
  "email": "john.updated@example.com",
  "phone": "987-654-3210"
}

### 7. Location Management

#### 7.1. Add Location
POST http://localhost:3000/admin/location/add HTTP/1.1
Content-Type: application/json

[
    { "name": "Arpara" },
    { "name": "Atharo Mile" },
    { "name": "Awria" },
    { "name": "Baghachra" },
    { "name": "Bashgram" },
    { "name": "Benapole" },
    { "name": "Bhanga" },
    { "name": "Board Bazar" },
    { "name": "Charavita" },
    { "name": "Chowgacha" },
    { "name": "Chuknagar" },
    { "name": "Chutipur" },
    { "name": "Dhaka" },
    { "name": "Dhaka-Gabtoli" },
    { "name": "Faridpur" },
    { "name": "Gazipur" },
    { "name": "Godkhali" },
    { "name": "Jamtola" },
    { "name": "Jessore" },
    { "name": "Jhikorgacha" },
    { "name": "Kalia" },
    { "name": "Keshabpur" },
    { "name": "Kolarowa" },
    { "name": "Kolkata" },
    { "name": "Kopilmoni" },
    { "name": "Laxmipasha" },
    { "name": "Magura" },
    { "name": "Maleker Bari" },
    { "name": "Mawa" },
    { "name": "Monirampur" },
    { "name": "Nabinagar" },
    { "name": "Narail" },
    { "name": "Navaron" },
    { "name": "Paikgacha" },
    { "name": "Patkelghata" },
    { "name": "Purapara" },
    { "name": "Purulia" },
    { "name": "Satkhira" },
    { "name": "Savar" },
    { "name": "Shib bari" },
    { "name": "Shima Khali" },
    { "name": "Shyamnagor" },
    { "name": "Tala" },
    { "name": "Tongi" },
    { "name": "Tularampur" },
    { "name": "Ulashi" },
    { "name": "Vatiapara" }
]
####7.2 update location
PUT http://localhost:3000/admin/location/1/update HTTP/1.1
Content-Type: application/json

{
  "name": "Abdullahpur"
}
#### 7.3. Remove location
DELETE http://localhost:3000/admin/location/1/delete HTTP/1.1


#### 7.4 Search location by ID
GET http://localhost:3000/location/1 HTTP/1.1

#### 7.4 Get all locations
GET http://localhost:3000/locations/ HTTP/1.1



### 5. Admin Actions

#### 5.1. Add New Bus/Train
POST http://localhost:3000/buses HTTP/1.1
Content-Type: application/json

{
  "bus_name": "DHAKA Express",
  "type": "Non AC",
  "departure_time": "2024-09-20T08:00:00Z",
  "arrival_time": "2024-09-20T12:00:00Z",
  "fromlocation": 1,
  "tolocation": 9
}
###View buses

GET  http://localhost:3000/buses/ HTTP/1.1

#### 5.2. Delete Bus/Train
DELETE http://localhost:3000/admin/bus/:bus_id HTTP/1.1

### 6. Additional Admin Actions

#### 6.1. Add Seat
POST http://localhost:3000/admin/seats HTTP/1.1
Content-Type: application/json

{
  "busId": 2,
  "seat_number": "A1",
  "is_available": true
}
### update seat
PUT http://localhost:3000/admin/seats/update/1 HTTP/1.1
Content-Type: application/json

{
  "seat_number": "B1",
  "is_available": false
}

###deleteseat
DELETE http://localhost:3000/admin/seats/delete/1 HTTP/1.1

###fetch seat
GET http://localhost:3000/seats/23 HTTP/1.1

###fetch seat of a bus
GET http://localhost:3000/seats/bus/1 HTTP/1.1
###fetch seat of a bus
GET http://localhost:3000/seats/bus/2 HTTP/1.1
###fetch seat of a train
GET http://localhost:3000/seats/train/1 HTTP/1.1

### config
PUT http://localhost:3000/admin/seats/update-config/2  HTTP/1.1
Content-Type: application/json

{
  "seat_number": "A2",
  "configuration": "2-2"
}
###add multiple seats for a bus
POST http://localhost:3000/admin/seats/bus/add-seats/1 HTTP/1.1
Content-Type: application/json

{
  "totalSeats": 48,
  "configuration": "2-2"
}

###Search for buses or trains based on location and time
GET http://localhost:3000/search?from=9&to=11&date=2024-09-20

###Search for buses or trains based on location and time
GET http://localhost:3000/search?from=1&to=11&date=2024-09-20
###Search for buses or trains based on location and time
GET http://localhost:3000/search?from=9&to=14&date=2024-09-20
###Search for buses or trains based on location and time
GET http://localhost:3000/search?from=1&to=9&date=2024-09-20
###Search for buses or trains based on location and time
GET http://localhost:3000/search?from=11&to=19&date=2024-09-20